name: Send Email on Frontend Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Send email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Frontend Build ${{ job.status }} - ${{ github.repository }}
          to: samuelpregnolatto@gmail.com
          from: GitHub Actions <samuelpregnolatto@gmail.com>
          body: |
            O workflow de build para ${{ github.repository }} foi concluído.
            Status: ${{ job.status }}
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref }}
            Veja os detalhes: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
